### ISSUE TITLE
error: login failed

### ISSUE THREAD

**Issue by qt06** [KartikTalwar/Duolingo#138]
```py
import duolingo
dlg = duolingo.Duolingo('asdfg','aaaaaaaa')
```
I got a error.
The response is not a json.
It's a html string.

**Comment by browniegnome** [comment]
Having the same issue. Providing both username and password gets me a JSON error. When excepting this error, i get a HTML string

**Comment by kevincoulson-jpg** [comment]
same issue:
`Traceback (most recent call last):

  File "<stdin>", line 1, in <module>

  File "C:\Users\kevin\AppData\Local\Programs\Python\Python312\Lib\site-packages\duolingo.py", line 66, in __init__
    self._login()

  File "C:\Users\kevin\AppData\Local\Programs\Python\Python312\Lib\site-packages\duolingo.py", line 105, in _login
    attempt = request.json()
              ^^^^^^^^^^^^^^

  File "C:\Users\kevin\AppData\Local\Programs\Python\Python312\Lib\site-packages\requests\models.py", line 978, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)

requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`

**Comment by AsteroidOrangeJuice** [comment]
FYI there's a fork here: https://github.com/iSteve-O/Duolingo
