### ISSUE TITLE
JSON Decode error on initiation

### ISSUE THREAD

**Issue by HumanBot000** [KartikTalwar/Duolingo#142]
```py
lingo  = duolingo.Duolingo('User', 'PW')
print(lingo.get_user_info())
```

results in 

```Traceback (most recent call last):
 
    lingo  = duolingo.Duolingo('User', 'PW')
  File "frfrfrfrfedevr\duolingo.py", line 66, in __init__
    self._login()
  File "jemff4gfh4rb\duolingo.py", line 105, in _login
    attempt = request.json()
  File "dhb3ufh34fffh403bgf\requests\models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by HumanBot000** [comment]
I thinks it's a copy of https://github.com/KartikTalwar/Duolingo/issues/128#issue-1590536442
