### ISSUE TITLE
any updates?

### ISSUE THREAD

**Issue by aseedb** [KartikTalwar/Duolingo#144]
This repo is great but it doesn't seem to be maintained anymore. Has anyone forked it and continue to maintain it and to adapt to duolingo api changes?

**Comment by iSteve-O** [comment]
@aseedb if you are still interested I forked it, updated the readme and added some examples... 

https://github.com/iSteve-O/Duolingo

**Comment by Fly1337** [comment]
@iSteve-O Hey!
I tried using the fork (which should ideally really be upstreamed to here) but I came to some issues

When trying to get the vocab of the current language

Traceback (most recent call last):
  File "duo.py", line 5, in <module>
    vocab = lingo.get_vocabulary(language_abbr='fr')
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "\.venv\Lib\site-packages\duolingo.py", line 550, in get_vocabulary
    overview = overview_request.json()
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "\.venv\Lib\site-packages\requests\models.py", line 978, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

And when trying to use a different language

Traceback (most recent call last):
  File "duo.py", line 5, in <module>
    vocab = lingo.get_vocabulary(language_abbr='ru')
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "\.venv\Lib\site-packages\duolingo.py", line 546, in get_vocabulary
    self._switch_language(language_abbr)
  File "\.venv\Lib\site-packages\duolingo.py", line 254, in _switch_language
    parse = request.json()['tracking_properties']
            ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'bool' object is not subscriptable

**Comment by udondan** [comment]
I have re-written this in TypeScript: https://github.com/udondan/duolingo - only read-only, no changing actions, as I do not need it and it will be hard to test without messing up my account.

@Fly1337 from what I can see the get_vocabulary no longer is supported by the duo api
