### ISSUE TITLE
get_vocabulary method doesn't work 

### ISSUE THREAD

**Issue by suleymanyaman** [KartikTalwar/Duolingo#57]
get_vocabulary method throws a JSON error like the following:

> Traceback (most recent call last):
  File "C:/Users/asus/.PyCharmCE2017.3/config/scratches/duolingo_auth.py", line 9, in <module>
    print(lingo.get_vocabulary(language_abbr="es")) 
  File "C:\Users\asus\AppData\Local\Programs\Python\Python36-32\lib\site-packages\duolingo.py", line 240, in get_vocabulary
    overview = overview_request.json()
  File "C:\Users\asus\AppData\Local\Programs\Python\Python36-32\lib\site-packages\requests\models.py", line 892, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\asus\AppData\Local\Programs\Python\Python36-32\lib\json\__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "C:\Users\asus\AppData\Local\Programs\Python\Python36-32\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\asus\AppData\Local\Programs\Python\Python36-32\lib\json\decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None

**Comment by suleymanyaman** [comment]
Actually, it has just worked when I passed the password to the lingo object.

**Comment by joshcoales** [comment]
Fixed, closing ticket
