### ISSUE TITLE
Several methods are not working...

### ISSUE THREAD

**Issue by addohm** [KartikTalwar/Duolingo#60]
The one I am most interested in is `get_audio_url`.

```
>>> u.get_audio_url('hello', language_abbr='en')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/addohm/anaconda3/envs/DuolingoUpdate/lib/python3.7/site-packages/duolingo.py", line 300, in get_audio_url
    tts_voice = self._get_voice(language_abbr, rand=random, voice=voice)
  File "/home/addohm/anaconda3/envs/DuolingoUpdate/lib/python3.7/site-packages/duolingo.py", line 276, in _get_voice
    self._process_tts_voices()
  File "/home/addohm/anaconda3/envs/DuolingoUpdate/lib/python3.7/site-packages/duolingo.py", line 269, in _process_tts_voices
    voices_js = re.search('duo\.tts_multi_voices = {.+};', self._homepage).group(0)
AttributeError: 'NoneType' object has no attribute 'group'
```

Others include:
```
>>> u.get_translations(['de', 'du'])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/addohm/anaconda3/envs/DuolingoUpdate/lib/python3.7/site-packages/duolingo.py", line 222, in get_translations
    target = self.user_data.language_data.keys()[0]
TypeError: 'dict_keys' object does not support indexing
```

```
>>> u.get_vocabulary()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/addohm/anaconda3/envs/DuolingoUpdate/lib/python3.7/site-packages/duolingo.py", line 240, in get_vocabulary
    overview = overview_request.json()
  File "/home/addohm/anaconda3/envs/DuolingoUpdate/lib/python3.7/site-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/home/addohm/anaconda3/envs/DuolingoUpdate/lib/python3.7/site-packages/simplejson/__init__.py", line 518, in loads
    return _default_decoder.decode(s)
  File "/home/addohm/anaconda3/envs/DuolingoUpdate/lib/python3.7/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/home/addohm/anaconda3/envs/DuolingoUpdate/lib/python3.7/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

Also, you may want to be specific about the requirements in the readme.md.  What python version is required here?  Is that perhaps where my issues are coming from?  Or is it perhaps that Duolingo has changed their API\JSON?

**Comment by clauney** [comment]
get_audio_url isn't working because it depends on _process_tts_voices scraping the duolingo homepage, and the homepage no longer has the voices exposed in the source like the function depends on.

A hit of the internet wayback machine at archive.org (view-source:http://web.archive.org/web/20170914233223/https://www.duolingo.com/) showed an older page with this string in the HTML:
duo.tts_multi_voices = {"dn": ["dn/ruben"], "el": ["el/maria"], "fr": ["fr", "fr/mathieu"], "en": ["en/salli"], "pt": ["pt/vitoria"], "ru": ["ru/julia"], "tr": ["tr/filiz"], "nb": ["nb/liv"], "de": ["de"], "ko": ["ko/hyejin"], "it": ["it/carla"], "sv": ["sv/astrid"], "cy": ["cy/gwyneth"], "es": ["es"], "cs": ["cs/female01_cs_cz"], "ca": ["ca/eurcatalanfemale"], "ro": ["ro/female01"], "da": ["da"], "ja": ["ja/mizuki"], "pl": ["pl/maja"]};

When fed into the logic in the _process_tts_voices method, it populates self._tts_voices properly.

The compression of the homepage into one long line also breaks the re.search that parses the cloudfront server into self._cloudfront_server, further borking the URL. 

In the end, after spackle, I did get it to return voices like: 
duo.get_audio_url('chaque', 'fr')
Out[108]: 'https://d35aaqx5ub95lt.cloudfront.net/tts/fr/mathieu/token/chaque'

But then I get a not authorized trying to browse them. I'm sure the cloudfront CDN is protected by some key generated by some JS in the page / app. It may not be too hard to fix, but will ultimately be brittle as Duolingo changes / refactors stuff.

**Comment by joshcoales** [comment]
All should be fixed and tested now, closing ticket
